# Configuration Nixpacks pour ASSURMINUT CRM
# Force l'utilisation du serveur Express au lieu de build statique

[variables]
NODE_ENV = "production"
PORT = "5000"

[phases.build]
dependsOn = ["install"]
cmds = ["npm run build"]

[phases.install]
dependsOn = ["setup"]
cmds = ["npm ci"]

[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x", "openssl", "curl", "wget"]

[start]
cmd = "npm start"

# Forcer le provider pour éviter la détection SPA
[providers]
node = true